version: "3.7"

services:

  database:
    image: postgres:9.5
    restart: unless-stopped
    ports: 
      - "5432:5432"
    expose: 
      - "5432"
    volumes:
      - easypeasyData:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: easypeasy

  marble-app:
    image: node:chakracore-8.11.1
    volumes: 
      - ./:/home/node/app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on: 
      - database
    working_dir: /home/node/app
    environment:
      - AUTH_SECRET=asdf;lkj
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=admin
      - DATABASE_USER=admin
      - DATABASE_DB=easypeasy
      - PORT=8080
      - REACT_APP_API=localhost
    command: "npm start"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8081

volumes: 
  easypeasyData: